name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GHC and Cabal
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.10'

      - name: Update package list
        run: cabal update

      - name: Build
        run: cabal build

      - name: Run tests (if you add any)
        run: |
          cabal test || echo "No tests defined"
